version: "3"
services:
    neo4j:
        image: neo4j:latest
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - data:/data
        environment:
            NEO4J_AUTH: none
            NEO4J_dbms_directories_import: /ingest
            NEO4J_dbms_memory_pagecache_size: 1G
            NEO4J_dbms.memory.heap.initial_size: 1G
            NEO4J_dbms_memory_heap_max__size: 1G
        network_mode: bridge
volumes:
    data:
        driver: local